
CREATE TABLE Nomina (
    ID SERIAL PRIMARY KEY,
    CI VARCHAR(20) NOT NULL UNIQUE,
    PN VARCHAR(50) NOT NULL,
    PN2 VARCHAR(100) DEFAULT NULL,
    PA VARCHAR(50) NOT NULL,
    PA2 VARCHAR(100) DEFAULT NULL,
    Activo VARCHAR(2) NOT NULL DEFAULT 'si' CHECK (Activo IN ('si', 'no')),
    Cargo VARCHAR(100) NOT NULL,
    FechaBA DATE DEFAULT NULL,
    FP VARCHAR(255) DEFAULT NULL
);


CREATE TABLE usuario (
    Usuario VARCHAR(20) PRIMARY KEY,
    Contrasena VARCHAR(255) NOT NULL,
    Permisos SMALLINT NOT NULL DEFAULT 1,
    Nombre VARCHAR(150) DEFAULT NULL,
    Apellido VARCHAR(150) DEFAULT NULL,
    Cargo VARCHAR(100) DEFAULT NULL,

);


CREATE TABLE Jornadas (
    ID SERIAL PRIMARY KEY,
    FJ DATE NOT NULL,
    Anfitrion VARCHAR(20) NOT NULL,
    Entregas INTEGER DEFAULT 0,
    Analistas TEXT,
 
);


CREATE TABLE Entregas (
    ID SERIAL PRIMARY KEY,
    ID_Jornada INTEGER NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    CI VARCHAR(20) NOT NULL,
    Apellido VARCHAR(100) NOT NULL,
    Descripcion TEXT,
    FOREIGN KEY (ID_Jornada) REFERENCES Jornadas(ID)
);
